version: '3'
services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright-tests
    volumes:
      - .:/app
    ports:
      - "9323:9323"
    working_dir: /app